"""`civic-slm new-recipe` — interactive YAML recipe scaffold.

Why a CLI scaffold: the smallest YAML a YamlRecipe accepts is four required
fields (jurisdiction, state, vendor, start_url) and one optional. That's
still four spots where a typo silently breaks the agent's discovery prompt
(wrong vendor → wrong template) or the manifest entry (wrong state → wrong
data/raw layout). Walking the maintainer through them with validation
catches these at scaffold time rather than at first crawl.

The command also surfaces the SOURCES.md audit gate. That's a documentation
contract, not a runtime check — easy to forget, easy to skip. A pointer at
scaffold time is the right place to mention it.
"""

from __future__ import annotations

import re
from pathlib import Path

import typer

from civic_slm.logging import configure, get_logger

log = get_logger(__name__)

_SLUG_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
_STATE_RE = re.compile(r"^[A-Z]{2}$")
_VENDORS = ("civicplus", "iqm2", "granicus", "legistar", "primegov", "municode")
_RECIPES_DIR = Path(__file__).parent / "recipes"


def main(
    slug: str = typer.Option(None, "--slug", help="Jurisdiction slug (kebab-case)."),
    state: str = typer.Option(None, "--state", help="2-letter postal code."),
    vendor: str = typer.Option(
        None,
        "--vendor",
        help=f"Vendor template — one of: {', '.join(_VENDORS)}.",
    ),
    start_url: str = typer.Option(None, "--start-url", help="Agenda center / calendar URL."),
    youtube_channel: str | None = typer.Option(
        None,
        "--youtube-channel",
        help="Optional channel URL for `discover_videos`. Leave blank to skip.",
    ),
    out_dir: Path = typer.Option(
        _RECIPES_DIR,
        "--out-dir",
        help="Where to write `<slug>.yaml`. Default is the project recipes dir.",
    ),
    force: bool = typer.Option(
        False, "--force", help="Overwrite an existing `<slug>.yaml` instead of refusing."
    ),
) -> None:
    """Generate a YAML recipe stub for a new U.S. jurisdiction.

    Prompts for any field not passed on the command line. Validates slug
    shape, state code, and vendor before writing.
    """
    configure()
    slug = slug or typer.prompt("Jurisdiction slug (kebab-case, e.g. santa-monica)")
    if not _SLUG_RE.match(slug):
        raise typer.BadParameter(f"slug {slug!r} is not kebab-case ASCII (a-z, 0-9, hyphens).")

    state = (state or typer.prompt("State (2-letter code, e.g. CA)")).strip().upper()
    if not _STATE_RE.match(state):
        raise typer.BadParameter(f"state {state!r} is not a 2-letter postal code.")

    if not vendor:
        typer.echo("\nAvailable vendor templates:")
        for v in _VENDORS:
            typer.echo(f"  - {v}")
        vendor = typer.prompt("Vendor (one of the above)")
    vendor = vendor.strip().lower()
    if vendor not in _VENDORS:
        raise typer.BadParameter(
            f"vendor {vendor!r} is not recognized. Pick one of: {', '.join(_VENDORS)}."
        )

    start_url = start_url or typer.prompt("Start URL (the agenda center / calendar page)")
    start_url = start_url.strip()
    if not start_url.startswith(("http://", "https://")):
        raise typer.BadParameter(f"start_url {start_url!r} must begin with http:// or https://.")

    if youtube_channel is None:
        youtube_channel = typer.prompt(
            "YouTube channel URL (optional — press Enter to skip)", default=""
        ).strip()

    out_path = out_dir / f"{slug}.yaml"
    if out_path.exists() and not force:
        raise typer.BadParameter(
            f"{out_path} already exists. Use --force to overwrite, or pick a different --slug."
        )

    yaml_lines = [
        f"# {slug}, {state} — generated by `civic-slm new-recipe`.",
        "#",
        "# IMPORTANT: gated on the docs/SOURCES.md ToS audit. The recipe will be",
        "# discovered by the crawler as soon as it lands; do not run a real crawl",
        "# until a maintainer has filed an audit entry and flipped Decision: GO.",
        f"jurisdiction: {slug}",
        f"state: {state}",
        f"vendor: {vendor}",
        f"start_url: {start_url}",
        "doc_type_default: agenda",
    ]
    if youtube_channel:
        yaml_lines.append(f"youtube_channel: {youtube_channel}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(yaml_lines) + "\n", encoding="utf-8")

    typer.echo(f"\nWrote {out_path}")
    typer.echo(
        "\nNext steps:\n"
        f"  1. Add a docs/SOURCES.md entry for `{slug}` (PENDING is fine).\n"
        f"  2. Have a maintainer flip Decision: GO after reviewing the ToS.\n"
        f"  3. uv run civic-slm crawl {slug} --max 5 --since 2025-09-01\n"
        "  4. Spot-check `data/raw/manifest.jsonl` and the landed PDFs.\n"
    )


if __name__ == "__main__":
    typer.run(main)
